### ISSUE TITLE
Modelado de datos

### ISSUE THREAD

**Issue by sorejuela** [ISCOUTB/AG-StellarGather#1]
Realizar el modelado de datos que tendrá la aplicación

**Comment by IsaacDev2024** [comment]
![Image](https://github.com/user-attachments/assets/95e0f1c1-3748-43e6-a4e0-2aece6709d44)

**Comment by sorejuela** [comment]
![Image](https://github.com/user-attachments/assets/b31448ee-94a0-49e9-8e21-e84715c11ecc)

**Comment by jairoserrano** [comment]
adelante.
