### ISSUE TITLE
Elección de Motor SQL/NoSQL

### ISSUE THREAD

**Issue by sorejuela** [ISCOUTB/AG-StellarGather#19]

**Comment by Soraruwave** [comment]
SQL:
PostgreSQL:
- Es gratuito
- Soporta relaciones complejas y consultas
- Tiene buena integración con servicios en la nube y microservicios
- Compatible con ORM como SQLAlchemy (para Python) que se integra bien con FastAPI

No SQL:
MongoDB:
- Es también gratuito (MongoDB Atlas para soluciones en la nube)
- Maneja bien datos no estructurados y semi-estructurados
- Permite almacenar grandes volúmenes de datos y ofrece escalabilidad

**Comment by DiazLuis-Code** [comment]
No SQL:
MongoDB:
- Es también open-sorce (MongoDB Atlas para soluciones en la nube)
- Maneja bien datos no estructurados y semi-estructurados
- Permite almacenar grandes volúmenes de datos y ofrece escalabilidad

**Comment by jairoserrano** [comment]
adelante
