### ISSUE TITLE
Ordenar SQL/NoSQL

### ISSUE THREAD

**Issue by sorejuela** [ISCOUTB/AG-StellarGather#2]

**Comment by Soraruwave** [comment]
Bases de datos SQL:
- Usuarios
- Registros
- Eventos
- Comentarios y calificaciones

Bases de datos No SQL:
- Interacciones
- Notificaciones
- Errores

**Comment by DiazLuis-Code** [comment]
Bases de datos No SOL:

Comentarios y calificaciones:
Feedback textual y numérico que los usuarios añaden sobre registros o entidades.

Interacciones:
Acciones realizadas por los usuarios o sistemas con los datos almacenados, como lecturas, escrituras o actualizaciones.

Notificaciones:
Mensajes o alertas generados por la base de datos para informar sobre cambios, eventos o condiciones específicas.

Errores:
Problemas o fallos que ocurren durante las operaciones con la base de datos, como inconsistencias de datos o fallos en las consultas.

**Comment by jairoserrano** [comment]
adelante
