### ISSUE TITLE
Esquema de la API de microservicio de gestión SQL

### ISSUE THREAD

**Issue by Soraruwave** [ISCOUTB/AG-StellarGather#21]
Aquí se mostrará el esquema de la API de microservicio de usuarios

**Comment by IsaacDev2024** [comment]
Endpoints
- POST /usuarios: Registrar un nuevo usuario.
    Request: { "nombre": "Juan", "email": "juan@example.com", "contraseña": "12345", "preferencias": {...} }
    Response: 201 Created { "usuario_id": 1, "nombre": "Juan", ... }
- POST /login: Autenticación de usuario.
    Request: { "email": "juan@example.com", "contraseña": "12345" }
    Response: 200 OK { "token": "jwt_token" }
- GET /usuarios/{usuario_id}: Obtener detalles de un usuario.
    Request: Headers: Authorization: Bearer {token}
    Response: 200 OK { "usuario_id": 1, "nombre": "Juan", "email": "juan@example.com", "preferencias": {...} }
- PUT /usuarios/{usuario_id}: Actualizar perfil de usuario.
    Request: Headers: Authorization: Bearer {token}, Body: { "nombre": "Juan Carlos", "preferencias": {...} }
    Response: 200 OK { "usuario_id": 1, "nombre": "Juan Carlos", ... }

**Comment by jairoserrano** [comment]
https://editor.swagger.io/

**Comment by IsaacDev2024** [comment]
openapi: 3.0.3
info:
  title: StellarGather API - User, Event, and Registration Management
  description: |-
    API for managing users, events, and user registrations in the StellarGather platform. This API is responsible for handling user data, event information, and registration details using an SQL database (PostgreSQL).
  version: 1.0.0
  contact:
    email: support@stellargather.com
servers:
  - url: https://api.stellargather.com/v1
    description: Production server
tags:
  - name: users
    description: User management operations
  - name: events
    description: Event management operations
  - name: registrations
    description: Registration management operations
paths:
  /users:
    get:
      tags:
        - users
      summary: Retrieve all users
      description: Retrieve a list of all registered users in the system.
      operationId: getUsers
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Server error
    post:
      tags:
        - users
      summary: Create a new user
      description: Add a new user to the system by providing necessary details.
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid user input
  /users/{userId}:
    get:
      tags:
        - users
      summary: Get a user by ID
      description: Retrieve user details by user ID.
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            description: ID of the user to retrieve
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
    put:
      tags:
        - users
      summary: Update user details
      description: Update information of an existing user by ID.
      operationId: updateUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            description: ID of the user to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User updated successfully
        '400':
          description: Invalid input
        '404':
          description: User not found
    delete:
      tags:
        - users
      summary: Delete a user
      description: Delete a user by ID from the system.
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            description: ID of the user to delete
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found

  /events:
    get:
      tags:
        - events
      summary: Retrieve all events
      description: Get a list of all available events in the system.
      operationId: getEvents
      responses:
        '200':
          description: A list of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '500':
          description: Server error
    post:
      tags:
        - events
      summary: Create a new event
      description: Add a new event to the system by providing necessary details.
      operationId: createEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: Event created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Invalid event input

  /events/{eventId}:
    get:
      tags:
        - events
      summary: Get event by ID
      description: Retrieve details of an event by event ID.
      operationId: getEventById
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
            description: ID of the event to retrieve
      responses:
        '200':
          description: Event found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '404':
          description: Event not found
    put:
      tags:
        - events
      summary: Update an event
      description: Update details of an existing event by ID.
      operationId: updateEvent
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
            description: ID of the event to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: Event updated successfully
        '400':
          description: Invalid input
        '404':
          description: Event not found
    delete:
      tags:
        - events
      summary: Delete an event
      description: Remove an event from the system by ID.
      operationId: deleteEvent
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
            description: ID of the event to delete
      responses:
        '204':
          description: Event deleted successfully
        '404':
          description: Event not found

  /registrations:
    get:
      tags:
        - registrations
      summary: Retrieve all registrations
      description: Get a list of all user registrations for events.
      operationId: getRegistrations
      responses:
        '200':
          description: A list of registrations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Registration'
        '500':
          description: Server error
    post:
      tags:
        - registrations
      summary: Create a new registration
      description: Register a user for an event.
      operationId: createRegistration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Registration'
      responses:
        '201':
          description: Registration created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Registration'
        '400':
          description: Invalid registration input

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the user
        username:
          type: string
        email:
          type: string
        full_name:
          type: string
      required:
        - username
        - email

    Event:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the event
        name:
          type: string
        description:
          type: string
        location:
          type: string
        date:
          type: string
          format: date-time
      required:
        - name
        - date

    Registration:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the registration
        user_id:
          type: integer
        event_id:
          type: integer
        status:
          type: string
          enum:
            - registered
            - canceled
      required:
        - user_id
        - event_id

**Comment by IsaacDev2024** [comment]
```
openapi: 3.0.3
info:
  title: StellarGather API - User, Event, and Registration Management
  description: |-
    API for managing users, events, and user registrations in the StellarGather platform. This API is responsible for handling user data, event information, and registration details using an SQL database (PostgreSQL).
  version: 1.0.0
  contact:
    email: support@stellargather.com
servers:
  - url: https://api.stellargather.com/v1
    description: Production server
tags:
  - name: users
    description: User management operations
  - name: events
    description: Event management operations
  - name: registrations
    description: Registration management operations
paths:
  /users:
    get:
      tags:
        - users
      summary: Retrieve all users
      description: Retrieve a list of all registered users in the system.
      operationId: getUsers
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Server error
    post:
      tags:
        - users
      summary: Create a new user
      description: Add a new user to the system by providing necessary details.
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid user input
  /users/{userId}:
    get:
      tags:
        - users
      summary: Get a user by ID
      description: Retrieve user details by user ID.
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            description: ID of the user to retrieve
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
    put:
      tags:
        - users
      summary: Update user details
      description: Update information of an existing user by ID.
      operationId: updateUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            description: ID of the user to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User updated successfully
        '400':
          description: Invalid input
        '404':
          description: User not found
    delete:
      tags:
        - users
      summary: Delete a user
      description: Delete a user by ID from the system.
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            description: ID of the user to delete
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found

  /events:
    get:
      tags:
        - events
      summary: Retrieve all events
      description: Get a list of all available events in the system.
      operationId: getEvents
      responses:
        '200':
          description: A list of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '500':
          description: Server error
    post:
      tags:
        - events
      summary: Create a new event
      description: Add a new event to the system by providing necessary details.
      operationId: createEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: Event created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Invalid event input

  /events/{eventId}:
    get:
      tags:
        - events
      summary: Get event by ID
      description: Retrieve details of an event by event ID.
      operationId: getEventById
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
            description: ID of the event to retrieve
      responses:
        '200':
          description: Event found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '404':
          description: Event not found
    put:
      tags:
        - events
      summary: Update an event
      description: Update details of an existing event by ID.
      operationId: updateEvent
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
            description: ID of the event to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: Event updated successfully
        '400':
          description: Invalid input
        '404':
          description: Event not found
    delete:
      tags:
        - events
      summary: Delete an event
      description: Remove an event from the system by ID.
      operationId: deleteEvent
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
            description: ID of the event to delete
      responses:
        '204':
          description: Event deleted successfully
        '404':
          description: Event not found

  /registrations:
    get:
      tags:
        - registrations
      summary: Retrieve all registrations
      description: Get a list of all user registrations for events.
      operationId: getRegistrations
      responses:
        '200':
          description: A list of registrations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Registration'
        '500':
          description: Server error
    post:
      tags:
        - registrations
      summary: Create a new registration
      description: Register a user for an event.
      operationId: createRegistration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Registration'
      responses:
        '201':
          description: Registration created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Registration'
        '400':
          description: Invalid registration input

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the user
        username:
          type: string
        email:
          type: string
        full_name:
          type: string
      required:
        - username
        - email

    Event:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the event
        name:
          type: string
        description:
          type: string
        location:
          type: string
        date:
          type: string
          format: date-time
      required:
        - name
        - date

    Registration:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the registration
        user_id:
          type: integer
        event_id:
          type: integer
        status:
          type: string
          enum:
            - registered
            - canceled
      required:
        - user_id
        - event_id
```

**Comment by jairoserrano** [comment]
adelant
