### ISSUE TITLE
Realizar el frontend de la página de autenticación y registro

### ISSUE THREAD

**Issue by IsaacDev2024** [ISCOUTB/AG-StellarGather#22]

**Comment by DiazLuis-Code** [comment]
![Image](https://github.com/user-attachments/assets/ae8728a4-4df1-45d3-a533-3290bd95c600)

**Comment by DiazLuis-Code** [comment]
Se realizó actualización de la autenticación:
![Image](https://github.com/user-attachments/assets/08bf38e4-eb64-4842-ad40-ef212f5caa30)

**Comment by DiazLuis-Code** [comment]
Registro
![Image](https://github.com/user-attachments/assets/d98b80fc-1dde-4fa2-8046-0b6fb3e66697)

**Comment by DiazLuis-Code** [comment]
Código en el repositorio
