### ISSUE TITLE
Esquema de la API de microservicio de gestión NoSQL

### ISSUE THREAD

**Issue by IsaacDev2024** [ISCOUTB/AG-StellarGather#23]

**Comment by IsaacDev2024** [comment]
openapi: 3.0.3
info:
  title: StellarGather NoSQL Service API
  description: |-
    API para gestionar interacciones, errores, comentarios, calificaciones y notificaciones en el servicio NoSQL de StellarGather. Este servicio utiliza bases de datos NoSQL (MongoDB) para almacenar datos no estructurados y semi-estructurados.
  termsOfService: http://stellargather.com/terms/
  contact:
    email: support@stellargather.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://api.stellargather.com/nosql/v1
tags:
  - name: comments
    description: Gestión de comentarios y calificaciones
  - name: notifications
    description: Gestión de notificaciones
  - name: interactions
    description: Registro de interacciones de los usuarios
  - name: errors
    description: Registro y consulta de errores del sistema

paths:
  /comments:
    post:
      tags:
        - comments
      summary: Crear un nuevo comentario
      description: Crear un nuevo comentario para un evento al que el usuario ha asistido
      operationId: createComment
      requestBody:
        description: Datos del comentario
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
        required: true
      responses:
        '201':
          description: Comentario creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '400':
          description: Datos inválidos
    get:
      tags:
        - comments
      summary: Obtener comentarios de un evento
      description: Obtiene una lista de comentarios para un evento específico
      operationId: getCommentsByEvent
      parameters:
        - name: eventId
          in: query
          description: ID del evento para obtener los comentarios
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
        '404':
          description: Evento no encontrado
  /ratings:
    post:
      tags:
        - comments
      summary: Enviar calificación para un evento
      description: Registrar una calificación para un evento
      operationId: rateEvent
      requestBody:
        description: Datos de la calificación
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rating'
        required: true
      responses:
        '201':
          description: Calificación registrada exitosamente
        '400':
          description: Datos inválidos
  /notifications:
    post:
      tags:
        - notifications
      summary: Crear una nueva notificación
      description: Crear una nueva notificación para un usuario registrado
      operationId: createNotification
      requestBody:
        description: Datos de la notificación
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
        required: true
      responses:
        '201':
          description: Notificación creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '400':
          description: Datos inválidos
    get:
      tags:
        - notifications
      summary: Obtener notificaciones de un usuario
      description: Devuelve la lista de notificaciones para un usuario específico
      operationId: getNotifications
      parameters:
        - name: userId
          in: query
          description: ID del usuario
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Notificaciones obtenidas exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
        '404':
          description: Usuario no encontrado
  /interactions:
    post:
      tags:
        - interactions
      summary: Registrar una interacción de usuario
      description: Registrar una interacción de un usuario con un evento o función
      operationId: createInteraction
      requestBody:
        description: Datos de la interacción
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Interaction'
        required: true
      responses:
        '201':
          description: Interacción registrada exitosamente
        '400':
          description: Datos inválidos
    get:
      tags:
        - interactions
      summary: Obtener interacciones de un usuario
      description: Devuelve todas las interacciones de un usuario específico
      operationId: getUserInteractions
      parameters:
        - name: userId
          in: query
          description: ID del usuario
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Interacciones obtenidas exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Interaction'
        '404':
          description: Usuario no encontrado
  /errors:
    post:
      tags:
        - errors
      summary: Registrar un error del sistema
      description: Registrar un error del sistema ocurrido durante una operación
      operationId: logError
      requestBody:
        description: Datos del error
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
        required: true
      responses:
        '201':
          description: Error registrado exitosamente
        '400':
          description: Datos inválidos
    get:
      tags:
        - errors
      summary: Obtener errores del sistema
      description: Devuelve una lista de errores registrados en el sistema
      operationId: getErrors
      responses:
        '200':
          description: Lista de errores obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'

components:
  schemas:
    Comment:
      type: object
      properties:
        commentId:
          type: string
        userId:
          type: string
        eventId:
          type: string
        commentText:
          type: string
        timestamp:
          type: string
          format: date-time
    Rating:
      type: object
      properties:
        ratingId:
          type: string
        userId:
          type: string
        eventId:
          type: string
        ratingValue:
          type: integer
          format: int32
          minimum: 1
          maximum: 5
    Notification:
      type: object
      properties:
        notificationId:
          type: string
        userId:
          type: string
        message:
          type: string
        read:
          type: boolean
        timestamp:
          type: string
          format: date-time
    Interaction:
      type: object
      properties:
        interactionId:
          type: string
        userId:
          type: string
        eventId:
          type: string
        interactionType:
          type: string
        timestamp:
          type: string
          format: date-time
    Error:
      type: object
      properties:
        errorId:
          type: string
        errorMessage:
          type: string
        errorCode:
          type: integer
        timestamp:
          type: string
          format: date-time

**Comment by IsaacDev2024** [comment]
```
openapi: 3.0.3
info:
  title: StellarGather NoSQL Service API
  description: |-
    API para gestionar interacciones, errores, comentarios, calificaciones y notificaciones en el servicio NoSQL de StellarGather. Este servicio utiliza bases de datos NoSQL (MongoDB) para almacenar datos no estructurados y semi-estructurados.
  termsOfService: http://stellargather.com/terms/
  contact:
    email: support@stellargather.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://api.stellargather.com/nosql/v1
tags:
  - name: comments
    description: Gestión de comentarios y calificaciones
  - name: notifications
    description: Gestión de notificaciones
  - name: interactions
    description: Registro de interacciones de los usuarios
  - name: errors
    description: Registro y consulta de errores del sistema

paths:
  /comments:
    post:
      tags:
        - comments
      summary: Crear un nuevo comentario
      description: Crear un nuevo comentario para un evento al que el usuario ha asistido
      operationId: createComment
      requestBody:
        description: Datos del comentario
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
        required: true
      responses:
        '201':
          description: Comentario creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '400':
          description: Datos inválidos
    get:
      tags:
        - comments
      summary: Obtener comentarios de un evento
      description: Obtiene una lista de comentarios para un evento específico
      operationId: getCommentsByEvent
      parameters:
        - name: eventId
          in: query
          description: ID del evento para obtener los comentarios
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
        '404':
          description: Evento no encontrado
  /ratings:
    post:
      tags:
        - comments
      summary: Enviar calificación para un evento
      description: Registrar una calificación para un evento
      operationId: rateEvent
      requestBody:
        description: Datos de la calificación
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rating'
        required: true
      responses:
        '201':
          description: Calificación registrada exitosamente
        '400':
          description: Datos inválidos
  /notifications:
    post:
      tags:
        - notifications
      summary: Crear una nueva notificación
      description: Crear una nueva notificación para un usuario registrado
      operationId: createNotification
      requestBody:
        description: Datos de la notificación
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
        required: true
      responses:
        '201':
          description: Notificación creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '400':
          description: Datos inválidos
    get:
      tags:
        - notifications
      summary: Obtener notificaciones de un usuario
      description: Devuelve la lista de notificaciones para un usuario específico
      operationId: getNotifications
      parameters:
        - name: userId
          in: query
          description: ID del usuario
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Notificaciones obtenidas exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
        '404':
          description: Usuario no encontrado
  /interactions:
    post:
      tags:
        - interactions
      summary: Registrar una interacción de usuario
      description: Registrar una interacción de un usuario con un evento o función
      operationId: createInteraction
      requestBody:
        description: Datos de la interacción
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Interaction'
        required: true
      responses:
        '201':
          description: Interacción registrada exitosamente
        '400':
          description: Datos inválidos
    get:
      tags:
        - interactions
      summary: Obtener interacciones de un usuario
      description: Devuelve todas las interacciones de un usuario específico
      operationId: getUserInteractions
      parameters:
        - name: userId
          in: query
          description: ID del usuario
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Interacciones obtenidas exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Interaction'
        '404':
          description: Usuario no encontrado
  /errors:
    post:
      tags:
        - errors
      summary: Registrar un error del sistema
      description: Registrar un error del sistema ocurrido durante una operación
      operationId: logError
      requestBody:
        description: Datos del error
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
        required: true
      responses:
        '201':
          description: Error registrado exitosamente
        '400':
          description: Datos inválidos
    get:
      tags:
        - errors
      summary: Obtener errores del sistema
      description: Devuelve una lista de errores registrados en el sistema
      operationId: getErrors
      responses:
        '200':
          description: Lista de errores obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Error'

components:
  schemas:
    Comment:
      type: object
      properties:
        commentId:
          type: string
        userId:
          type: string
        eventId:
          type: string
        commentText:
          type: string
        timestamp:
          type: string
          format: date-time
    Rating:
      type: object
      properties:
        ratingId:
          type: string
        userId:
          type: string
        eventId:
          type: string
        ratingValue:
          type: integer
          format: int32
          minimum: 1
          maximum: 5
    Notification:
      type: object
      properties:
        notificationId:
          type: string
        userId:
          type: string
        message:
          type: string
        read:
          type: boolean
        timestamp:
          type: string
          format: date-time
    Interaction:
      type: object
      properties:
        interactionId:
          type: string
        userId:
          type: string
        eventId:
          type: string
        interactionType:
          type: string
        timestamp:
          type: string
          format: date-time
    Error:
      type: object
      properties:
        errorId:
          type: string
        errorMessage:
          type: string
        errorCode:
          type: integer
        timestamp:
          type: string
          format: date-time
```

**Comment by jairoserrano** [comment]
adelante
