### ISSUE TITLE
Infraestructura

### ISSUE THREAD

**Issue by sorejuela** [ISCOUTB/AG-StellarGather#5]

**Comment by IsaacDev2024** [comment]
1. Arquitectura General
El proyecto StellarGather sigue una arquitectura basada en microservicios y datos, utilizando varios contenedores Docker para manejar diferentes funcionalidades. Cada microservicio tiene su propio contenedor y base de datos, garantizando una escalabilidad y mantenibilidad independientes.

2. Componentes principales
A. Microservicio de Usuarios (API)
- Lenguaje: Python
- Framework: FastAPI (para manejar las solicitudes HTTP)
- Imagen de Docker: Usamos una imagen de Python 3.12-slim como base.
- Dependencias principales:
   - FastAPI para la API.
   - SQLAlchemy para la interacción con la base de datos (PostgreSQL).
   - Pydantic para la validación de datos.
- Base de Datos: PostgreSQL, ejecutada en un contenedor Docker separado.

B. Microservicio de Eventos y Registros
Cada uno de estos microservicios sigue una estructura similar al microservicio de Usuarios. Estos microservicios también utilizan:
- Lenguaje y Framework: Python con FastAPI.
- Imagen Docker: Basada en Python 3.12-slim.
- Base de Datos: PostgreSQL para cada uno de estos microservicios, corriendo en contenedores separados.

C. Microservicio de Notificaciones, Comentarios/Calificaciones, Interacciones
- Lenguaje y Framework: Python con FastAPI.
- Base de datos: MongoDB
- Imagen Docker: Python 3.12-slim para el microservicio y MongoDB Atlas para la base de datos.

D. Frontend Web (Página Web)
- Servidor web: Nginx
- Imagen de Docker: Usamos la imagen nginx:18 para servir la web estática.
- Archivos web: HTML, CSS, JavaScript, servidos desde Nginx.

3. Puertos expuestos:
Cada servicio tiene sus propios puertos expuestos para acceder desde fuera de Docker. Se elegiran los puertos en el camino.

 4. Herramientas y Servicios de Apoyo
- ORM: Usamos SQLAlchemy para la interacción con las bases de datos PostgreSQL.
- Autenticación: En desarrollo futuro, podemos integrar algo como OAuth2 con JWT para autenticación segura de los usuarios.

**Comment by sorejuela** [comment]
C. Microservicio de Notificaciones, Comentarios/Calificaciones, Interacciones
- Lenguaje y Framework: Python con FastAPI.
- Base de datos: MongoDB
- Imagen Docker: Python 3.12-slim para el microservicio y MongoDB Atlas para la base de datos.

D. Frontend Web (Página Web)
- Servidor web: Nginx
- Imagen de Docker: Usamos la imagen nginx:18 para servir la web estática.
- Archivos web: HTML, CSS, JavaScript, servidos desde Nginx.

3. Puertos expuestos:
Cada servicio tiene sus propios puertos expuestos para acceder desde fuera de Docker. Se elegiran los puertos en el camino.

4. Herramientas y Servicios de Apoyo
ORM: Usamos SQLAlchemy para la interacción con las bases de datos PostgreSQL.
Autenticación: En desarrollo futuro, podemos integrar algo como OAuth2 con JWT para autenticación segura de los usuarios.

**Comment by jairoserrano** [comment]
adelante, tienen que reducir el número de microservicios
